### ISSUE TITLE
rebuilds shelf every time you run a query?

### ISSUE THREAD

**Issue by cogcomp-dev** [google/categorybuilder#3] opened 2018-06-13 22:40 UTC
I've followed the installation instructions and saw the expected console output during initialization. However, now I ran the command `python categorybuilder.py hunger emergency` and I'm seeing similar output to the init process -- which took hours on the host machine, and a repeat of which would make this tool unusable. 
```
(py27) [mssammon@shelley categorybuilder] >python category_builder.py  hunger emergency
	Creating shelf. Processed 10000 lines out of 200000
	Creating shelf. Processed 20000 lines out of 200000
	Creating shelf. Processed 30000 lines out of 200000
	Creating shelf. Processed 40000 lines out of 200000
	Creating shelf. Processed 50000 lines out of 200000
	Creating shelf. Processed 60000 lines out of 200000
	Creating shelf. Processed 70000 lines out of 200000
```

**Comment by amahabal** [comment] 2018-06-13 23:59
That is not the expected behavior. The shelf should get created once and reused thereafter (although note that there are two shelfs involved, both created by the init).

What do you mean by "host machine"? Is there more than one machine involved in what you are doing?

A few questions about your setup: what is the OS? It will also be useful to see the output of "ls -asl".

Thanks!
  Abhijit

**Comment by cogcomp-dev** [comment] 2018-06-14 01:40
never mind. I was expecting an application, not an example... but maybe you can extend the functionality a little bit to be interactive, just for those of us who are pressed for time :-)

**Comment by cogcomp-dev** [comment] 2018-06-14 01:45
Sorry, reacted (closed issue) before realizing you had responded. Host machine: I'm working remotely, running the process on a reasonably good server running Ubuntu 16.04. 
The default python version on this machine is 3.6; I used miniconda to set up an environment with python 2.6 to run your script.

output of `ls -asl`:
```
total 6680924
      4 drwxrwsr-x 4 mssammon cs_danr       4096 Jun 13  2018 .
      4 drwxrwsr-x 7 mssammon cs_danr       4096 Jun 13 15:34 ..
      4 -rw-rw-r-- 1 mssammon cs_danr       1177 Jun 12 12:27 analogy.py
      0 -rw-rw-r-- 1 mssammon cs_danr          0 Jun 13  2018 aslout.txt
1028304 -rw-rw-r-- 1 mssammon cs_danr 1052979042 Jun 12 15:40 candidate_release-f-to-i.csv.bz2
 568680 -rw-rw-r-- 1 mssammon cs_danr  582323067 Jun 12 15:39 candidate_release-i-to-f.csv.bz2
    232 -rw-rw-r-- 1 mssammon cs_danr     237157 Jun 12 12:27 category_builder_paper.pdf
      4 -rw-rw-r-- 1 mssammon cs_danr       1278 Jun 12 12:27 category_builder.py
      8 -rw-rw-r-- 1 mssammon cs_danr       6056 Jun 13 12:23 category_builder_util.py
      8 -rw-rw-r-- 1 mssammon cs_danr       6056 Jun 12 12:27 category_builder_util.py~
      8 -rw-rw-r-- 1 mssammon cs_danr       7923 Jun 13 14:35 category_builder_util.pyc
      4 -rw-rw-r-- 1 mssammon cs_danr       1101 Jun 12 12:27 CONTRIBUTING.md
  31240 -rw-rw-r-- 1 mssammon cs_danr   31987976 Jun 13 18:18 f-to-i-shelf.bak
3570140 -rw-rw-r-- 1 mssammon cs_danr 3654710166 Jun 13 18:18 f-to-i-shelf.dat
  31244 -rw-rw-r-- 1 mssammon cs_danr   31987976 Jun 13 18:18 f-to-i-shelf.dir
      4 drwxrwsr-x 9 mssammon cs_danr       4096 Jun 13 12:23 .git
      4 -rw-rw-r-- 1 mssammon cs_danr         42 Jun 12 12:27 .gitattributes
      4 -rw-rw-r-- 1 mssammon cs_danr         13 Jun 12 12:27 .gitignore
      4 -rw-rw-r-- 1 mssammon cs_danr        759 Jun 12 12:27 initialize.py
   6340 -rw-rw-r-- 1 mssammon cs_danr    6491622 Jun 13 19:47 i-to-f-shelf.bak
1438320 -rw-rw-r-- 1 mssammon cs_danr 1472616426 Jun 13 19:47 i-to-f-shelf.dat
   6340 -rw-rw-r-- 1 mssammon cs_danr    6491622 Jun 13 19:47 i-to-f-shelf.dir
     12 -rw-rw-r-- 1 mssammon cs_danr      11358 Jun 12 12:27 LICENSE
      4 -rw-rw-r-- 1 mssammon cs_danr         79 Jun 12 12:27 .mailmap
      4 drwxrwsr-x 2 mssammon cs_danr       4096 Jun 13 12:22 __pycache__
      4 -rw-rw-r-- 1 mssammon cs_danr       2894 Jun 12 12:27 README.md
```

**Comment by amahabal** [comment] 2018-06-14 03:48
Thanks! I think I know what the problem is, will send a fix in the next 24 hours.

The problem: on my system, the shelf file is named "i-to-f.shelf", and I am checking for this file to not repeat shelf creation. However, on your system it gets named "i-to-f.shelf.dat" (plus two more files; this is not unexpected). The fix will be to check for any large file with a i-to-f.shelf prefix .

--Abhijit

**Comment by amahabal** [comment] 2018-06-14 04:35
Can you check if this is now fixed? You will not need to regenerate shelves: the current ones should work.

Thanks for the report,
  Abhijit

**Comment by cogcomp-dev** [comment] 2018-06-14 10:36
Yes, that did it -- thanks!

**Closed as completed** 2018-06-14 16:21 UTC
